const words = {
  english: {
    signupDynamic: 'Signup',
    emailDynamic: 'Email',
    passwordDynamic: 'Password',
    confirmDynamic: 'Confirm Password',
    submitDynamic: 'Submit',
    settingsDynamic: 'Settings',
    languageDynamic: 'Language',
    modeDynamic: 'Mode',
    light: 'Light',
    dark: 'Dark',
    loginDynamic: `Login`,
    homeDynamic: 'Home',
    citiesDynamic: 'Cities',
    dashboardDynamic: 'Dashboard',
    logoutDynamic: 'Logout',
    createItineraryDynamic: 'Create Itinerary',
    titleDynamic: 'Title',
    imageDynamic: 'Image',
    editItineraryDynamic: 'Edit / Add Details',
    cityDynamic: 'City',
    priceRangeDynamic: 'Price Range',
    durationDynamic: 'Duration',
    activitiesDyanmic: 'Activities',
    addActivityDynamic: 'Add Activity',
    locationDynamix: 'Location',
    deleteMsg:
      'Are you sure you want to do this? It will permanently delete the itinerary along with all activities you have added to it, as well as reviews others have left you.'
  },
  french: {
    signupDynamic: `S'inscrire`,
    emailDynamic: 'Email',
    passwordDynamic: 'Mot de Passe',
    confirmDynamic: 'Confirmez le Mot de Passe',
    submitDynamic: 'Soumettre',
    settingsDynamic: 'Réglages',
    languageDynamic: 'La langue',
    modeDynamic: 'Mode',
    light: 'Lumière',
    dark: 'Foncé',
    loginDynamic: `S'identifier`,
    homeDynamic: 'Home',
    citiesDynamic: 'Villes',
    dashboardDynamic: 'Dashboard',
    logoutDynamic: 'Connectez -Out',
    createItineraryDynamic: 'Create Itinerary',
    titleDynamic: 'Title',
    imageDynamic: 'Image',
    editItineraryDynamic: 'Edit / Add Details',
    cityDynamic: 'ciudad',
    priceRangeDynamic: 'Price Range',
    durationDynamic: 'Duration',
    activitiesDyanmic: 'Activities',
    addActivityDynamic: 'Add Activity',
    locationDynamix: 'Location',
    deleteMsg:
      'Are you sure you want to do this? It will permanently delete the itinerary along with all activities you have added to it, as well as reviews others have left you.'
  },
  german: {
    signupDynamic: `Anmelden`,
    emailDynamic: 'Email',
    passwordDynamic: 'Passwort',
    confirmDynamic: 'Passwort Bestätigen',
    submitDynamic: 'Submit',
    settingsDynamic: 'Einstellungen',
    languageDynamic: 'Sorache',
    modeDynamic: 'Modus',
    light: 'Hell',
    dark: 'Dunkel',
    loginDynamic: `Anmeldung`,
    homeDynamic: 'Startseite',
    citiesDynamic: 'Städte',
    dashboardDynamic: 'Übersichtsseite',
    logoutDynamic: 'Ausloggen',
    createItineraryDynamic: 'Create Itinerary',
    titleDynamic: 'Title',
    imageDynamic: 'Image',
    editItineraryDynamic: 'Edit / Add Details',
    cityDynamic: 'ciudad',
    priceRangeDynamic: 'Price Range',
    durationDynamic: 'Duration',
    activitiesDyanmic: 'Activities',
    addActivityDynamic: 'Add Activity',
    locationDynamix: 'Location',
    deleteMsg:
      'Are you sure you want to do this? It will permanently delete the itinerary along with all activities you have added to it, as well as reviews others have left you.'
  },
  spanish: {
    signupDynamic: `Regístrate`,
    emailDynamic: 'Correo Electrónico',
    passwordDynamic: 'Contraseña',
    confirmDynamic: 'Confirmar Contraseña',
    submitDynamic: 'Enviar',
    settingsDynamic: 'Configuraciones',
    languageDynamic: 'Idioma',
    modeDynamic: 'Modo',
    light: 'Ligero',
    dark: 'Oscuro',
    loginDynamic: `Iniciar sesión`,
    homeDynamic: 'Página Principal',
    citiesDynamic: 'Ciudades',
    dashboardDynamic: 'Dashboard',
    logoutDynamic: 'Cerrar Sesión',
    createItineraryDynamic: 'Crear Itinerario',
    titleDynamic: 'Titulo',
    imageDynamic: 'Imagen',
    editItineraryDynamic: 'Edit / Add Details',
    cityDynamic: 'Ciudad',
    priceRangeDynamic: 'Rango de Precios',
    durationDynamic: 'Duración',
    activitiesDyanmic: 'Actividad',
    addActivityDynamic: 'Agregar Actividad',
    locationDynamix: 'Ubicación',
    deleteMsg:
      'Are you sure you want to do this? It will permanently delete the itinerary along with all activities you have added to it, as well as reviews others have left you.'
  }
}

export default words
